# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/guillermo/Downloads/Linux_Unreal_Engine_5.4.3
GAMEPROJECTFILE =/home/guillermo/Documents/Unreal Projects/TopDownTest/TopDownTest.uproject

TARGETS = \
	TopDownTest-Linux-DebugGame  \
	TopDownTest-Linux-Shipping  \
	TopDownTest \
	TopDownTestEditor-Linux-DebugGame  \
	TopDownTestEditor-Linux-Shipping  \
	TopDownTestEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TopDownTestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TopDownTestEditor-Linux-Debug


TopDownTest-Linux-DebugGame:
	 $(PROJECTBUILD) TopDownTest Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDownTest-Linux-Shipping:
	 $(PROJECTBUILD) TopDownTest Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDownTest:
	 $(PROJECTBUILD) TopDownTest Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDownTestEditor-Linux-DebugGame:
	 $(PROJECTBUILD) TopDownTestEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDownTestEditor-Linux-Shipping:
	 $(PROJECTBUILD) TopDownTestEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TopDownTestEditor:
	 $(PROJECTBUILD) TopDownTestEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
